import {
  FaAws,
  FaBrain,
  FaCloud,
  FaCode,
  FaDatabase,
  FaMicrosoft,
  FaPython,
  FaRobot,
  FaServer,
  FaShieldAlt,
} from 'react-icons/fa'
import {
  SiDjango,
  SiDocker,
  SiFastapi,
  SiFirebase,
  SiGooglecloud,
  SiKubernetes,
  SiLangchain,
  SiMysql,
  SiNextdotjs,
  SiNodedotjs,
  SiNumpy,
  SiOpenai,
  SiPandas,
  SiPostgresql,
  SiPydantic,
  SiReact,
  SiRedis,
  SiTailwindcss,
  SiTypescript,
} from 'react-icons/si'
import { TbApi, TbBrain, TbCloudCode, TbTopologyStar } from 'react-icons/tb'

const icons = {
  agent: FaRobot,
  aiApi: SiOpenai,
  api: TbApi,
  async: TbTopologyStar,
  aws: FaAws,
  azure: FaMicrosoft,
  brain: TbBrain,
  cicd: TbCloudCode,
  docker: SiDocker,
  events: TbTopologyStar,
  fastapi: SiFastapi,
  firebase: SiFirebase,
  gcp: SiGooglecloud,
  genkit: FaBrain,
  kubernetes: SiKubernetes,
  langchain: SiLangchain,
  langsmith: TbTopologyStar,
  mcp: TbTopologyStar,
  microservices: FaServer,
  mysql: SiMysql,
  next: SiNextdotjs,
  node: SiNodedotjs,
  ollama: FaRobot,
  pandas: SiPandas,
  pipeline: FaCode,
  postgres: SiPostgresql,
  prompt: SiOpenai,
  pydantic: SiPydantic,
  python: FaPython,
  qdrant: FaDatabase,
  rag: FaDatabase,
  react: SiReact,
  redis: SiRedis,
  safety: FaShieldAlt,
  schema: FaDatabase,
  shadcn: FaCode,
  shield: FaShieldAlt,
  tailwind: SiTailwindcss,
  typescript: SiTypescript,
  numpy: SiNumpy,
  cloud: FaCloud,
  django: SiDjango,
}

export function SkillIcon({ name }) {
  const Icon = icons[name] ?? FaCode

  return <Icon aria-hidden="true" />
}
